name = "GeneralizedSDistributions"
uuid = "759b0772-debe-4df1-a45f-0e53fcd0f49c"
authors = ["Alex Knudson <aknudson@nevada.unr.edu>"]
version = "0.2.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[compat]
DifferentialEquations = "6.16, 7"
Distributions = "0.24, 0.25"
HypergeometricFunctions = "0.3"
LsqFit = "0.12"
QuadGK = "2.4"
julia = "1.4, 1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
